<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Category;
use App\Models\SubCategory;
use App\Models\SubCategoryProperty;
use App\Models\SubCategoryPropertyValue;

class NewCategoriesSeeder extends Seeder
{
    /**
     * Guides
     */
    // women = 1
    // clothes = 1
    // brand  = 4
    // duplicate boss = 26
    

   
    public function run(): void
    {
        // womens clothes brand  = 4
        // Oh Polly - 4 exist
        // Zara - 4 exist
        $womenClothingOptionData = collect([
            ["sub_category_property_id" => 4 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Sandro", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Sezane", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 4, "name" => "Zimmerman", "status" => 1, "created_at" => now(), "updated_at" => now()]
        ]);

        SubCategoryPropertyValue::insert($womenClothingOptionData->toArray());

    
        // womens accessories brand  = 13
        $womenAccessoriesOptionData = collect([
            ["sub_category_property_id" => 13 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Oh Polly", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Sandro", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Sezane", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
            ["sub_category_property_id" => 13, "name" => "Zimmerman", "status" => 1, "created_at" => now(), "updated_at" => now()]
    ]);

    SubCategoryPropertyValue::insert($womenAccessoriesOptionData->toArray());

    // womens shoes brand  = 8
    $womenShoesOptionData = collect([
        ["sub_category_property_id" => 8 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Jimmy Choo", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Oh Polly", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Sandro", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Sezane", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 8, "name" => "Zimmerman", "status" => 1, "created_at" => now(), "updated_at" => now()]
    ]);

    SubCategoryPropertyValue::insert($womenShoesOptionData->toArray());

    // mens clothes brand  = 18
    $menClothesOptionData = collect([
        ["sub_category_property_id" => 18 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Stone Island", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 18, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 18, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($menClothesOptionData->toArray());

    // mens accessories brand  = 26
    $menAccessoriesOptionData = collect([
        ["sub_category_property_id" => 26 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Stone Island", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 26, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 26, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($menAccessoriesOptionData->toArray());

    // mens shoes brand  = 22
    $menShoesOptionData = collect([
        ["sub_category_property_id" => 22 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Stone Island", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 22, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 22, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($menShoesOptionData->toArray());

    // 0-4 years  = 34
    $childrenClosthesOptionData = collect([
        ["sub_category_property_id" => 34 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 34, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 34, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($childrenClosthesOptionData->toArray());

    // girls  = 39
    $childrenGirlsClosthesOptionData = collect([
        ["sub_category_property_id" => 39 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 39, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 39, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($childrenGirlsClosthesOptionData->toArray());

    // boys  = 44
    $childrenBoysClosthesOptionData = collect([
        ["sub_category_property_id" => 44 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 44, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 44, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($childrenBoysClosthesOptionData->toArray());


    // teenage girls  = 49
    $teenageGirlsClosthesOptionData = collect([
        ["sub_category_property_id" => 49 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 49, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 49, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($teenageGirlsClosthesOptionData->toArray());

    // teenage boys  = 54
    $teenageBoysClosthesOptionData = collect([
        ["sub_category_property_id" => 54 , "name" => "Balenciaga", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Bottega Veneta", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Boss", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Burberry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "C.P Company", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Chador", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Chloe", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Christian Dior", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Christian Louboutin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Coach", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "D1 Milano", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Dolce & Gabbana", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Dsquared 2", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Emporio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Fendi", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Giorgio Armani", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Givenchy", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Gucci", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Hermes", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Keep sake the label", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Kiehls", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Louis Vuitton", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Maje", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Marc Jacobs", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Moncler", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Moschino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Mulburry", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Nass", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Off-White", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Roksanda", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Rolex", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Saint Laurent", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Tag Heur", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Valentino", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Versace", "status" => 1, "created_at" => now(), "updated_at" => now()],   
        ["sub_category_property_id" => 54, "name" => "Versace Jeans Couture", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Vilberquin", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "YSL", "status" => 1, "created_at" => now(), "updated_at" => now()],
        ["sub_category_property_id" => 54, "name" => "Zara", "status" => 1, "created_at" => now(), "updated_at" => now()],
    ]);

    SubCategoryPropertyValue::insert($teenageBoysClosthesOptionData->toArray());

    }
}
